version: "3"

services:
  crypto_mongo:
    build: crypto-exchange-MongoDB/
    restart: always
    image: node-mongo
    environment:
      - MONGODB_URI=
      - DATABASE=
      - HOST=

#mongodb:
#  image: mongo:latest
#  volumes:
#    - mongodb_volume:/data/db
#  restart: always
